### ISSUE TITLE
Divisions ought to be 1/x rather than x

### ISSUE THREAD

**Issue by xmacex** [stvnrlly/subharmoniclone#3]
I believe the intention is to set the divisions as $\frac{1}{x}$ rather than $x$ for the `division` parameter on creation, and later `set_division` for the four rhythms here

https://github.com/stvnrlly/subharmoniclone/blob/b628fad53ff7ae16367744b40665b82fcb5fbdaa/subharmoniclone.lua#LL418-L440

Chaning them from

```lua
  rhythm_1 = sub_lattice:new_pattern{
    action = function() play("r1") end,
    division = params:get("rhythm_1")
  }
  params:set_action("rhythm_1",function(x) rhythm_1:set_division(x) end)
```

to

```lua
  rhythm_1 = sub_lattice:new_pattern{
    action = function() play("r1") end,
    division = 1/params:get("rhythm_1")
    --         ﹋
  }
  params:set_action("rhythm_1",function(x) rhythm_1:set_division(1/x) end)
  --                                                             ﹋
```

seems to do it. Or do I understand incorrectly? My musicology knowledge is poor, but I know fast music is better haha 🏇 

Thanks for a cool script.

**Comment by stvnrlly** [comment]
Hmm, I can't now recall why I decided to do it this way, although I know that I changed it at least once before ending up with this setup. It appears to work the way that I intended it to, at least, with higher denominators meaning slower progression. 

Are you seeing a different behavior?

**Comment by xmacex** [comment]
Closing as myself being simply misguided, sorry about the confusion.
